### PR TITLE
Fix issues with latest flake8 version

### PR DESCRIPTION
**Pull request by A-CGray**
## Purpose

I noticed that flake8 was complaining about violations of [W503](https://www.flake8rules.com/rules/W503.html) in the latest version (v5.0.4) despite the fact that W503 is supposed to be ignored by default by flake8 because the thing W503 complains about is now actually considered best practice. 

Based on [this issue](https://github.com/PyCQA/flake8/issues/1687) it appears that the config handling behaviour was changed in v5 such that the fact that we include `w` in the `select` list enables all `W` checks, even though `W503` is in the `ignore` list.  

Since `E`, `W` and `F` are already [used by flake8 as default](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-select), I commented them out from the `select` list in our flake8 config file which means the `W503` check is no longer incorrectly re-enabled.

I think this should allow us to upgrade the version of flake8 we use.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by marcomangano — CHANGES_REQUESTED** [review]
Interesting, I assume you tested this locally?  A "centralized" `.flake8` file is not accepted anymore since  the early versions of v4 and I did not upgrade this in a while, but it looks like the issue persist with v5. For this reason, pretty much every line of my code exceeds the default length of 80. Are you copying the `.flake8` file in every repo/project folder?

**Comment by A-CGray** [comment]
> Interesting, I assume you tested this locally? A "centralized" `.flake8` file is not accepted anymore since the early versions of v4 and I did not upgrade this in a while, but it looks like the issue persist with v5. For this reason, pretty much every line of my code exceeds the default length of 80. Are you copying the `.flake8` file in every repo/project folder?

Unfortunately yes

**Comment by nwu63** [comment]
So the way I am dealing with this is by pointing VS Code to a specific config file. In my `settings.json` there is:
```
    "python.linting.flake8Args": [
        "--config=${env:HOME}/.config/flake8"
    ],
```

This works for me but in general environment variables are pretty poorly supported, which makes synced settings a bit tricky.

**Comment by marcomangano** [comment]
> Unfortunately yes
Does it mean that we would need to update all the repos to do this at test? In some cases (e.g. ADflow) we might even have conflicts with already existing files, if I am seeing this correctly

**Comment by A-CGray** [comment]
As a test, I ran flake8 v5.0.4 on ADflow and pyGeo with this new config and got these

ADflow:

```shell
flake8 .
./src_cs/build/complexify.py:507:9: A001 variable "type" is shadowing a python builtin
./src_cs/build/complexify.py:509:9: A001 variable "type" is shadowing a python builtin
```

pyGeo:

```shell
flake8 .

```

**Comment by marcomangano** [comment]
> ADflow:
> 
> ```shell
> flake8 .
> ./src_cs/build/complexify.py:507:9: A001 variable "type" is shadowing a python builtin
> ./src_cs/build/complexify.py:509:9: A001 variable "type" is shadowing a python builtin
> ```

`complexify` should be ignored, have you "merged" in the global `.flake8` the existing one in ADflow root folder?

**Comment by A-CGray** [comment]
> > ADflow:
> > ```shell
> > flake8 .
> > ./src_cs/build/complexify.py:507:9: A001 variable "type" is shadowing a python builtin
> > ./src_cs/build/complexify.py:509:9: A001 variable "type" is shadowing a python builtin
> > ```
> 
> `complexify` should be ignored, have you "merged" in the global `.flake8` the existing one in ADflow root folder?

oh, no I just overwrote it, which explains this

**Comment by marcomangano** [comment]
> oh, no I just overwrote it, which explains this

Yeah I feel [this procedure](https://github.com/mdolab/.github/blob/07cc10ded3a9a0b8d3c905b9ea497f8bb93f0ebe/azure/azure_style.yaml#L42-L58) should work fine, I think we can go on and merge

**Review by marcomangano — APPROVED** [review]

**Pull request merged**
