### PR TITLE
Update black version

### PR DESCRIPTION
**Pull request by A-CGray**
## Purpose

Today one of black's dependencies, click, made some breaking changes that broke black. They [released a fix](https://github.com/psf/black/pull/2966) but to get it we need to update to black v22.3.0, otherwise all of our black formatting checks that are run with GHA will fail. The other option is to pin `click<8.1.0` but that feels like a bad approach.

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by nwu63** [comment]
Is there really no way to use the older version? Feels kinda nuts that all previous versions of `black` can no longer be used. I guess the way to bypass this is to not use the GHA but instead manually downgrade `click` or something.

I'm just hesitant to update because there are formatting changes with 22 which means this would probably fail all the existing formatting in all repos. I guess I'm okay with bumping this but we have to be careful in updating this + getting everyone to update `black` on their machines.

**Comment by A-CGray** [comment]
My reading of the PR I linked to is that it's either upgrade to 22.3 or pin an old version of click, I could be misunderstanding though

**Comment by A-CGray** [comment]
Looks like this is now causing a failure in the azure jobs too

**Review by sseraj — APPROVED** [review]
I think we should just update the black version.

**Pull request merged**
