### PR TITLE
Use global .clang-format file and format all files

### PR DESCRIPTION
**Pull request by A-CGray**
## Purpose

I was about to add clang-format to the RLT repo and realised it was stupid to copy the same `.clang-format` and `clang-format.sh` files across multiple repos so I just moved them here. Personally I don't have an issue with running clang-format on all C/C++ files in a repo (rather than just those in a src/ directory) but I'm open to dissenting opinions

## Expected time until merged

End of this week (3 days)

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by nwu63 — APPROVED** [review]

**Comment by A-CGray** [comment]
@eirikurj sorry to bug but I'd like to get your blessing before merging this

**Comment by eirikurj** [comment]
Looks good. Seems to be copied over from `tacs_orig` with the `hpp` and `cpp` additions. Not that its critical, but do we need the `hpp` extension. Cant recall any repo of ours that uses that extension? I will make a PR to update `tacs_orig` to use this.

**Comment by eirikurj** [comment]
PR https://github.com/mdolab/tacs_orig/pull/86 is up. I expect you have the RLT repo already done?

**Comment by A-CGray** [comment]
> Looks good. Seems to be copied over from `tacs_orig` with the `hpp` and `cpp` additions. Not that its critical, but do we need the `hpp` extension. Cant recall any repo of ours that uses that extension? I will make a PR to update `tacs_orig` to use this.

Yeah I copied from tacs_orig, I added `.hpp` just for future-proofing

**Pull request merged**
